/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Kbu9VQEpcQU
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { JSX, SVGProps } from "react"

export function ChatLayout({children}:{children: React.ReactNode}) {
  return (
    <div className="grid grid-rows-[auto,1fr] w-full max-w-sm rounded-lg border">
      <div className="p-4 grid gap-4">
        <div className="flex items-center space-x-2">
          <img
            alt="User avatar"
            className="rounded-full"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
          <div className="rounded-lg bg-gray-100 dark:bg-gray-800 p-4 flex-1">
            <p className="text-sm">Hi there! How can I assist you today? You can ask me anything.</p>
          </div>
        </div>
        <div className="flex items-center space-x-2 justify-end">
          <div className="rounded-lg bg-blue-100 dark:bg-blue-400 p-4 flex-1 text-right">
            <p className="text-sm">I'm having trouble with my internet connection. Can you help?</p>
          </div>
          <img
            alt="AI avatar"
            className="rounded-full"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
        </div>
        <div className="flex items-center space-x-2">
          <img
            alt="User avatar"
            className="rounded-full"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
          <div className="rounded-lg bg-gray-100 dark:bg-gray-800 p-4 flex-1">
            <p className="text-sm">Sure! Let me check your connection.</p>
          </div>
        </div>
        <div className="flex items-center space-x-2 justify-end">
          <div className="rounded-lg bg-blue-100 dark:bg-blue-400 p-4 flex-1 text-right">
            <p className="text-sm">Thank you!</p>
          </div>
          <img
            alt="AI avatar"
            className="rounded-full"
            height="40"
            src="/placeholder.svg"
            style={{
              aspectRatio: "40/40",
              objectFit: "cover",
            }}
            width="40"
          />
        </div>
      </div>
      {children}
    </div>
  )
}



